version: '3.8'

services:
  backend:
    image: vipulsingh2200/think_back:latest
    container_name: mern-backend
    ports:
      - "5001:5001"
    env_file:
      - backend.env
    restart: unless-stopped

  frontend:
    image: vipulsingh2200/think_front:latest
    container_name: mern-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
