sonar.projectKey=singhvipul2200_mern-k8s-github-actions
sonar.organization=singhvipul2200
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.spec.js
